version: 2
updates:
  # - package-ecosystem: "npm"
  #   directory: /assets/
  #   schedule:
  #     interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
